### ISSUE TITLE
msys2 build failure

### ISSUE THREAD

**Issue by AireagoirSteam** [vasi/pixz#111]
tried to build on MSYS2/MinGW-w64 and it errors out not sure why but was wondering if it would be possable to make this compatable with msys2. heres the error message.

Thank you for any time taken on this
[log.txt](https://github.com/vasi/pixz/files/13453491/log.txt)

**Comment by vasi** [comment]
Thanks for the report! Can you share some more info about your build?

* What version of pixz are you building?
* What version of Windows and MSYS2 are you using, so someone could try to reproduce the error?
* What's the full set of commands you ran? Was there a `configure` step?
* What was the output from configure?
* What's in config.h?

**Comment by AireagoirSteam** [comment]
heres a file with e commands I ran and the msys2 version I have and the contents of config.h.
also the version of pixz used is the current master.
[msy2 version.txt](https://github.com/vasi/pixz/files/13515367/msy2.version.txt)

**Comment by vasi** [comment]
Do you know what msys2 [environment](https://www.msys2.org/docs/environments/) you're using to build pixz?

**Comment by vasi** [comment]
I tried using the UCRT64 environment, and what seems like the obvious packages: autoconf automake libtool make gcc pkgconf liblzma-devel libarchive-devel openssl-devel asciidoc. It builds fine! This is on Windows 10, with msys2-runtime 3.4.9-3. Checks mostly pass--there's no cppcheck package so that's skipped, and msys2 has no working chmod, so the permissions test fails.

Specifically relevant to this issue, sysconf() seems to exist in /usr/include/unistd.h.

I imagine you must be in some different environment, or using a different gcc, and so your includes are different.

**Comment by AireagoirSteam** [comment]
which gcc did you install? also found a package for cppcheck for ucrt64

**Comment by AireagoirSteam** [comment]
just added all packages you mentioned and started a ucrt enviroment up and no joy

**Comment by vasi** [comment]
Can you share the output of `pacman -Qe`? This is what I get:

```
asciidoc 10.2.0-3
autoconf-wrapper 20221207-1
automake-wrapper 20221207-1
base 2022.06-1
filesystem 2023.02.07-1
gcc 13.2.0-2
git 2.43.0-1
libarchive-devel 3.7.2-1
liblzma-devel 5.4.5-1
make 4.4.1-1
mingw-w64-ucrt-x86_64-cppcheck 2.12.1-1
msys2-runtime 3.4.9-3
openssl-devel 3.1.4-1
pkgconf 2.1.0-1
```

**Comment by vasi** [comment]
Also, can you check if you have sysconf in unistd? Run `grep sysconf /usr/include/unistd.h`

**Comment by AireagoirSteam** [comment]
> Here's a PR that ought to work: #112 . Passes tests (mostly), but there could easily be hidden breakages somewhere, Windows is weird.
> 
> I hope this was worth to you the several hours I spent on it!

Seems to build also thank you so much for the work and effort. 

The only minor niggle is I don't get the help read out when only type pixz and get a werid output.

$ pixz
²7zXZ☺i"Ì6

Seems to work otherwise.

**Comment by vasi** [comment]
Oh weird, windows' `isatty()` function does weird things. Should be fixed now in that branch.

Btw, I'm curious what your use case is for building against winapi, and not against cygwin (aka the plain 'gcc' package in msys2).

**Comment by AireagoirSteam** [comment]
I hadn't tried it with cygwin yet since I think you can have issues if install cygwin and msys2 installed together.

I can gove it a go with cygwin also to be honest just thought msys2 might have built easier since think I tried like 2 months back with cyvwin.
I'll try building with cygwin.

Also how would I build with the defences included in the exe static build think that is?

**Comment by vasi** [comment]
Oh sorry, I was unclear. I don't mean installing the "cygwin distribution" alongside msys2. What I was referring to is that msys2 has [two kinds of packages in it](https://www.msys2.org/wiki/How-does-MSYS2-differ-from-Cygwin/):

1. Mingw-based: Packages that link against the Windows APIs, and can't use POSIX (Unix-like) APIs. These packages have names like `mingw-w64-x86_64-curl`. You can build Windows API-ish code like this with compiler packages like `mingw-w64-ucrt-x86_64-gcc`.
2. Cygwin-based: Packages that link against the cygwin POSIX-compatibility layer, which in msys2 is named `msys-2.0.dll`. These packages have unprefixed names, like just `curl`. You can build POSIX-ish code like this with the compiler package just named `gcc`.

You have always been able to just install plain old `gcc` in msys2 and build a type-2 pixz without Windows-specific fixes being necessary. Of course, you'd also need dependencies that use the POSIX-compatibility layer and have unprefixed names, like `libarchive-devel`.

The changes I made in the linked PR are only helpful if you really must use the Win API libraries from msys2 (type 1), rather than the POSIX ones (type 2). So I was trying to ask whether it's important to you to specifically use a type-1 pixz, and why.

It sounds like maybe you're trying to build a static library that runs on other users' systems, without needing msys2.dll? That's a cool use case, is it working with my patch?

**Comment by AireagoirSteam** [comment]
I tried with mingwx64 before in ucrt it worked with patch but then that weid emoji stuff haven't cloned the repo again yet to test current stuff.

So should I try building in plain msys2?

**Comment by AireagoirSteam** [comment]
Also reason for a static buold just saves me copying all the dlls to the folder as the exe which can be tedious.

**Comment by vasi** [comment]
I merged the PR, including a fix to the tty-detection code (so your "weird emoji" issue should be gone now. Feel free to build from master in either mingw or msys2. I'll be closing the issue, but do go ahead and comment if anything else looks broken.
