### ISSUE TITLE
Android tar files fail to index

### ISSUE THREAD

**Issue by luke-jr** [vasi/pixz#120]
```
$ pixz -0 root.tar
(null)
Error reading archive entry
```

Using 1.0.7

**Comment by vasi** [comment]
Can you share anything about this file?

**Comment by luke-jr** [comment]
Created it with:

```
adb shell tar -cvp --exclude /sys --exclude /proc / 2>errout >root.tar
```

Several files had "Permission denied", but besides that stderr was only:

```
tar: unknown file type '140000'
tar: unknown file type '140000'
tar: unknown file type '140000'
```

**Comment by luke-jr** [comment]
Extraction with GNU tar, the only errors were "Cannot mknod: Operation not permitted" (because I didn't do it as root)

**Comment by vasi** [comment]
I tried this with an old Android phone I have,  and I can't reproduce. Can you build a file that has this problem, but which you're able to share with me?

**Comment by luke-jr** [comment]
`archive_read_next_header` is returning `ARCHIVE_FATAL` with `archive_error_string(ar)` returning `NULL`.

I cut a snippet out of my tar file and masked sensitive information (and gzip'd so GitHub accepted it) to make [test.tar.gz](https://github.com/user-attachments/files/18104261/test.tar.gz)

This file is listed as empty by GNU tar, but reproduces the error with pixz and libarchive's bsdtar.

AIUI, libarchive considers this scenario to be a bug, so I have reported it here also: https://github.com/libarchive/libarchive/issues/2434

**Comment by kientzle** [comment]
That `test.tar.gz` archive is complete nonsense.   It has a duplicate series of "L"ink records (an old GNU tar extension) and no "ustar" record at all.   In a valid tar archive, each entry is preceded by a series of header records.  Generally, no single header record should ever appear more than once, and the last of those header records is always a "ustar" record.   Having multiple "L" records is nonsensical, and the lack of a "ustar" record means that this file is simply malformed.

Libarchive's returning `ARCHIVE_FATAL` here is absolutely correct, since this archive is badly malformed.  Please report this to whoever maintains the software that created it.

The failure of libarchive to produce an error string is, however, certainly a bug in libarchive.  I'll see about getting that fixed.

**Comment by vasi** [comment]
Thanks for the context @kientzle . I don't really understand what's up with @luke-jr 's tar creating these odd tarballs, but I don't think I consider it a bug at this point that pixz doesn't know what to do with them.
