### ISSUE TITLE
distribute pixz.1 in tarball

### ISSUE THREAD

**Issue by andreasstieger** [vasi/pixz#50]
1.0.3 introduced a dependency on asciidoc and xslttranform (libxslt-tools). pixz.1 should be built at distribution time and shipped with the tarball.

**Comment by justinmayer** [comment]
Agreed. I had to add those as new build-time dependencies for the Homebrew formula, and I don't think those should actually be dependencies.

**Comment by wookietreiber** [comment]
Yes, I get how this can be annoying.

**Comment by cicku** [comment]
Should given a target like `make man` to let packagers determine whether building from source or not.

**Comment by wookietreiber** [comment]
@cicku There is a make target like that:

```
cd src
make pixz.1
```

This target, however, is depended upon by the `default` make target, so it is not optional.

**Comment by wookietreiber** [comment]
Currently, my thoughts on solving this is to make the `dist*` targets depend on the *generate all man pages* target. This way, the man page gets automatically injected into the release tarballs without the person who creates them having to care about it.

Those who build from a cloned repository would still need to generate the man page, but IMHO this is ok, i.e. if you are a *developer* who clones and builds from that, instead of a user who just cares about easily installing the software, you are more likely to accept to install the dependencies that are needed to create the man page.

Those are my thoughts on the issue.

**Comment by wookietreiber** [comment]
Seems I found a legit solution, see #51. Waiting to hear back from travis, then I will cut a new release.

**Comment by wookietreiber** [comment]
Done, new release is up. You do not need to depend on asciidoc anymore.

**Comment by justinmayer** [comment]
Thanks, Christian. I pushed a [new Homebrew formula](https://github.com/Homebrew/homebrew/pull/44149), so it should be available there once it's merged.

**Comment by cicku** [comment]
Fedora all branches pushed: [22](https://bodhi.fedoraproject.org/updates/FEDORA-2015-16233), [23](https://bodhi.fedoraproject.org/updates/FEDORA-2015-16233)
