### ISSUE TITLE
Show progress bar with `pv` and `pixz`

### ISSUE THREAD

**Issue by joelostblom** [vasi/pixz#58]
Hi,
Thanks for making `pixz`, I use it for all my backups and it works great! I especially appreciate the indexing feature.

I would like to display a progress bar during my backups and I found a couple of suggestions in [the answers to this SO question](http://superuser.com/questions/168749/is-there-a-way-to-see-any-tar-progress-per-file). For me, both suggestions work with `gzip`, `pigz` and `xz`, but not with `pixz`, `pxz` or when specifying multiple cores to   xz (`xz -T<num>`).

I just wanted to check if you knew right off the bat of any quick modification I could make to render that command usable with `pixz` or if it is not possible due to how `pixz` differs from the other compression utilities mentioned above.

For reference, the two suggestions from SO are
```
SIZE=`du -sk folder-with-big-files | cut -f 1`
tar cvf - folder-with-big-files | pv -p -s ${SIZE}k | pigz -c > big-files.tar.gz
```
and
```
tar cf - /folder-with-big-files -P | pv -s $(du -sb /folder-with-big-files | awk '{print $1}') | pigz > big-files.tar.gz
```

**Comment by vasi** [comment]
Things like that ought to work ok. I just did this (on OS X):

```
vasi$ SIZE=`du -sk trusty.pvm | cut -f 1`
vasi$ tar cf - trusty.pvm | pv -barpet -s ${SIZE}k | pixz > trusty.tpxz
```

Can you explain what happens when you try something like this? In what way does it not work?

**Comment by vasi** [comment]
Also, note that the rate estimates that pv gives may not be accurate at the start, because of how tools like pixz work.

For example, say you run `pixz -9`, and your CPU reports 8 cores. Pixz's queue size will be `ceil(1.3 * nCores + 1) = 11`, and for `-9` the block size will be 128 MiB. So pixz will start by reading `12 * 128 MiB = 1.5 GiB` before compression really gets started! This makes pv report a super high transfer rate. Afterwards, pixz will only read more as blocks are fully compressed, so the transfer rate will bounce around between zero and your disk's maximum rate. If you use the `-a` option to pv, it will show the average rate, which will eventually become reasonable.

**Comment by joelostblom** [comment]
Hey, thanks for the reply and sorry for not being more specific initially.

With "not working", I was referring to that the progress bar was not being displayed in the terminal. I did wait for a while before aborting, and it did show up when using `pigz` and waiting for a much shorter amount of time.  However, I tried again with `pixz` and now the progress bar does show up eventually, it just takes much longer than with `pigz` (40 s instead of 1-2 s on a 2.3 GB folder), which I guess is due to the increased compression rate.

Thanks for the reply and for pointing out the `-a` option.
